org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+UseG1GC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

android.useAndroidX=true
android.useFullClasspathForDexingTransform=true
org.gradle.warning.mode=none

# Toolchain discovery
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE

# Optional: silence AGP deprecation noise until you migrate
android.suppressUnsupportedCompileSdk=37
